const BLAST_FLASHSWAP_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const BLAST_SCRIPT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const BLAST_V2_POOL_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const BLAST_V3_POOL_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const BLAST_V2_CONTRACT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const BLAST_V3_CONTRACT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

module.exports = [BLAST_FLASHSWAP_PROVIDER_URL_LIST, BLAST_SCRIPT_PROVIDER_URL_LIST, BLAST_V2_POOL_PROVIDER_URL_LIST, BLAST_V3_POOL_PROVIDER_URL_LIST, BLAST_V2_CONTRACT_PROVIDER_URL_LIST, BLAST_V3_CONTRACT_PROVIDER_URL_LIST];
