const LINEA_FLASHSWAP_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const LINEA_SCRIPT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const LINEA_V2_POOL_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const LINEA_V3_POOL_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const LINEA_V2_CONTRACT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const LINEA_V3_CONTRACT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

module.exports = [LINEA_FLASHSWAP_PROVIDER_URL_LIST, LINEA_SCRIPT_PROVIDER_URL_LIST, LINEA_V2_POOL_PROVIDER_URL_LIST, LINEA_V3_POOL_PROVIDER_URL_LIST, LINEA_V2_CONTRACT_PROVIDER_URL_LIST, LINEA_V3_CONTRACT_PROVIDER_URL_LIST];
