const POLYGONZKEVM_FLASHSWAP_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const POLYGONZKEVM_SCRIPT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const POLYGONZKEVM_V2_POOL_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const POLYGONZKEVM_V3_POOL_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const POLYGONZKEVM_V2_CONTRACT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const POLYGONZKEVM_V3_CONTRACT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

module.exports = [
	POLYGONZKEVM_FLASHSWAP_PROVIDER_URL_LIST,
	POLYGONZKEVM_SCRIPT_PROVIDER_URL_LIST,
	POLYGONZKEVM_V2_POOL_PROVIDER_URL_LIST,
	POLYGONZKEVM_V3_POOL_PROVIDER_URL_LIST,
	POLYGONZKEVM_V2_CONTRACT_PROVIDER_URL_LIST,
	POLYGONZKEVM_V3_CONTRACT_PROVIDER_URL_LIST,
];
