const XLAYER_FLASHSWAP_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const XLAYER_SCRIPT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const XLAYER_V2_POOL_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const XLAYER_V3_POOL_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const XLAYER_V2_CONTRACT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

const XLAYER_V3_CONTRACT_PROVIDER_URL_LIST = [
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
	"YOUR_PROVIDER_URL",
];

module.exports = [
	XLAYER_FLASHSWAP_PROVIDER_URL_LIST,
	XLAYER_SCRIPT_PROVIDER_URL_LIST,
	XLAYER_V2_POOL_PROVIDER_URL_LIST,
	XLAYER_V3_POOL_PROVIDER_URL_LIST,
	XLAYER_V2_CONTRACT_PROVIDER_URL_LIST,
	XLAYER_V3_CONTRACT_PROVIDER_URL_LIST,
];
